# 自定义配置文件

# 数据配置
data:
  dataset_name: custom  # 使用自定义数据集
  custom_dataset_path: output/prepared_data/train_dataset.npz  # 训练数据集路径
  val_dataset_path: output/prepared_data/val_dataset.npz  # 验证数据集路径
  test_dataset_path: output/prepared_data/test_dataset.npz  # 测试数据集路径
  test_size: 0.2  # 测试集比例
  random_state: 42  # 随机种子
  save_path: null  # 数据保存路径

# 模型配置
model:
  model_type: multirocket_hydra  # 模型类型，可选 "hydra", "multirocket" 或 "multirocket_hydra"
  n_kernels: 32  # 卷积核数量
  n_groups: 64  # 每个扩张的组数
  max_dilations_per_kernel: 64  # 每个卷积核的最大扩张数
  n_features_per_kernel: 8  # 每个卷积核的特征数
  random_state: 42  # 随机种子
  n_jobs: -1  # 并行作业数，-1表示使用所有可用的CPU核心
  save_path: models/hydra_multirocket.pkl  # 模型保存路径

# 训练配置
training:
  epochs: 1  # 训练轮数（对于这种模型通常只需要一轮）
  verbose: true  # 是否显示详细信息
  save_best: true  # 是否保存最佳模型

# 输出目录
output_dir: output/models
