# 三分类模型配置文件（带校准分类器，简化版）- 2023年比特币15分钟数据

# 数据配置
data:
  dataset_name: custom  # 使用自定义数据集
  custom_dataset_path: output/data/prepared_data/train_dataset.npz  # 训练数据集路径
  val_dataset_path: output/data/prepared_data/val_dataset.npz  # 验证数据集路径
  test_dataset_path: output/data/prepared_data/test_dataset.npz  # 测试数据集路径
  test_size: 0.2  # 测试集比例
  random_state: 42  # 随机种子
  save_path: null  # 数据保存路径

# 模型配置
model:
  model_type: multirocket_hydra  # 模型类型，可选 "hydra", "multirocket" 或 "multirocket_hydra"
  n_kernels: 16  # 卷积核数量（减少）
  n_groups: 32  # 每个扩张的组数（减少）
  max_dilations_per_kernel: 32  # 每个卷积核的最大扩张数（减少）
  n_features_per_kernel: 4  # 每个卷积核的特征数（减少）
  random_state: 42  # 随机种子
  n_jobs: 1  # 并行作业数
  use_calibrated_classifier: true  # 使用校准分类器以获得更好的概率估计
  cv_folds: 3  # 校准分类器时使用的交叉验证折数（减少）
  save_path: models/calibrated_simple_hydra_multirocket.pkl  # 模型保存路径

# 训练配置
training:
  epochs: 1  # 训练轮数（对于这种模型通常只需要一轮）
  verbose: true  # 是否显示详细信息
  save_best: true  # 是否保存最佳模型

# 输出目录
output_dir: output/models/triclass_2023_calibrated_simple
